"""HTML story renderer with inlined thumbnail images."""

import base64
import io
import logging
import os
from html import escape

from PIL import Image

logger = logging.getLogger(__name__)


def _select_photos_for_event(photos: list[dict], max_photos: int = 3) -> list[dict]:
    """Pick up to max_photos representative photos from an event.

    If photos count <= max_photos, return all.
    Otherwise pick evenly-spaced indices (always includes first and last).
    """
    if len(photos) <= max_photos:
        return list(photos)
    if max_photos <= 1:
        return [photos[0]]
    if max_photos == 2:
        return [photos[0], photos[-1]]

    n = len(photos)
    indices = [round(i * (n - 1) / (max_photos - 1)) for i in range(max_photos)]
    indices = sorted(set(indices))
    return [photos[i] for i in indices]


def _encode_thumbnail_b64(file_path: str, max_width: int = 400) -> str | None:
    """Load image, resize to max_width, encode as base64 data URI (JPEG)."""
    if not file_path or not os.path.isfile(file_path):
        return None
    try:
        img = Image.open(file_path)
        img = img.convert("RGB")
        w, h = img.size
        if w > max_width:
            ratio = max_width / w
            new_size = (max_width, int(h * ratio))
            img = img.resize(new_size, Image.LANCZOS)

        buf = io.BytesIO()
        img.save(buf, format="JPEG", quality=75, optimize=True)
        b64 = base64.b64encode(buf.getvalue()).decode("ascii")
        return f"data:image/jpeg;base64,{b64}"
    except Exception as e:
        logger.warning(f"Thumbnail encoding failed for {file_path}: {e}")
        return None


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title}</title>
<style>
* {{ box-sizing: border-box; margin: 0; padding: 0; }}
body {{
    font-family: -apple-system, "PingFang SC", "Hiragino Sans GB", sans-serif;
    background: #fafaf8;
    color: #2a2a2a;
    line-height: 1.8;
    padding: 60px 20px;
}}
.container {{
    max-width: 720px;
    margin: 0 auto;
}}
h1 {{
    font-size: 2.4em;
    font-weight: 300;
    letter-spacing: 2px;
    margin-bottom: 16px;
    color: #1a1a1a;
}}
.stats {{
    color: #888;
    font-size: 0.95em;
    padding-bottom: 24px;
    border-bottom: 1px solid #e0e0dc;
    margin-bottom: 48px;
}}
.intro {{
    font-size: 1.15em;
    color: #444;
    margin-bottom: 56px;
    padding: 0 8px;
}}
.event {{
    margin-bottom: 72px;
}}
.event-meta {{
    display: flex;
    align-items: baseline;
    gap: 16px;
    margin-bottom: 16px;
    color: #666;
    font-size: 0.9em;
    letter-spacing: 1px;
}}
.event-date {{ font-weight: 500; color: #444; }}
.event-location {{ color: #888; }}
.event-mood {{
    color: #b08968;
    background: #f4ede4;
    padding: 2px 10px;
    border-radius: 12px;
    font-size: 0.85em;
}}
.event-summary {{
    font-size: 1.05em;
    color: #333;
    margin-bottom: 20px;
    line-height: 1.9;
}}
.photos {{
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
    gap: 8px;
    margin-top: 16px;
}}
.photos img {{
    width: 100%;
    height: 100%;
    object-fit: cover;
    border-radius: 4px;
    aspect-ratio: 4 / 3;
}}
.footer {{
    text-align: center;
    color: #aaa;
    font-size: 0.85em;
    padding-top: 40px;
    border-top: 1px solid #e0e0dc;
    margin-top: 80px;
}}
</style>
</head>
<body>
<div class="container">
<h1>{title}</h1>
<div class="stats">{stats}</div>
{intro_html}
{events_html}
<div class="footer">Generated by phototag · 本地 AI 回忆叙事</div>
</div>
</body>
</html>
"""


def render_story_html(
    title: str,
    stats_line: str,
    intro_narrative: str,
    events_with_photos: list[dict],
    max_photos_per_event: int = 3,
) -> str:
    """Render a complete self-contained HTML document for a story.

    Args:
        title: story title (H1)
        stats_line: stats summary (first line)
        intro_narrative: opening narrative paragraph
        events_with_photos: list of event dicts, each with 'photos' list containing
                            {'uuid', 'file_path'} entries
        max_photos_per_event: how many thumbnails to embed per event

    Returns a single HTML string with all images inlined as base64.
    """
    intro_html = ""
    if intro_narrative:
        intro_html = f'<div class="intro">{escape(intro_narrative)}</div>'

    event_blocks = []
    for e in events_with_photos:
        date = (e.get("start_time") or "")[:10]
        location = e.get("location_city") or "未知"
        mood = e.get("mood") or ""
        summary = e.get("summary") or ""

        photos = _select_photos_for_event(e.get("photos") or [], max_photos=max_photos_per_event)
        img_tags = []
        for ph in photos:
            data_uri = _encode_thumbnail_b64(ph.get("file_path", ""))
            if data_uri:
                img_tags.append(f'<img src="{data_uri}" alt="">')
        photos_html = ""
        if img_tags:
            photos_html = '<div class="photos">' + "".join(img_tags) + "</div>"

        mood_html = f'<span class="event-mood">{escape(mood)}</span>' if mood else ""

        event_blocks.append(
            '<div class="event">'
            f'<div class="event-meta">'
            f'<span class="event-date">{escape(date)}</span>'
            f'<span class="event-location">{escape(location)}</span>'
            f'{mood_html}'
            f'</div>'
            f'<div class="event-summary">{escape(summary)}</div>'
            f'{photos_html}'
            '</div>'
        )

    events_html = "\n".join(event_blocks)

    return HTML_TEMPLATE.format(
        title=escape(title),
        stats=escape(stats_line),
        intro_html=intro_html,
        events_html=events_html,
    )
